### ISSUE TITLE
better scheduling

### ISSUE THREAD

**Issue by binocarlos** [helixml/helix#144]
There are times when the scheduler makes terrible decisions - for example there is clearly a mistral7b running with no work and yet another model instance will start on another machine.

This is probably beause there is a race for all runners to pull the next task from the queue - the api has no control over which runner gets which job.

Runners are constantly reporting their status back to the api server (which is what drives the dashboard) - it feels like the api should have more say in:

> which job should end up on which runner

I think when a runner asks for a global job - the api should take into account what all the other runners are currently doing before deciding which job to return

For existing session jobs (i.e. a python process is asking for a job of a specific type because it has the weights already loaded) - we can keep the current behaviour as is

**Comment by lukemarsden** [comment]
We do already attempt to solve this by giving existing model instances a 2s head start on pulling jobs - we need to investigate why that isn't working

**Comment by lukemarsden** [comment]
This seems to be especially bad with finetuned models, or maybe I just got unlucky

**Comment by lukemarsden** [comment]
![IMG_2208](https://github.com/helixml/helix/assets/264658/9b756be1-9655-4837-90e2-24d49eb543a4)

Like here a single sequential chat session triggered the creation of four separate instances of the model
