### ISSUE TITLE
Model seems obsessed with more fine tuning of dataset

### ISSUE THREAD

**Issue by px3l** [helixml/helix#25]
Having submitted a document (random doc, outline of a fictional story), then asking what a character should do in the story, I keep being met with "Character should continue fine-tuning the data to improve the accuracy of the model." This seemed to be an inescapable answer, no matter how I posed the question.

It also does not appear to learn from any further conversation I have after the dataset is submitted.

**Comment by binocarlos** [comment]
![image](https://github.com/helixml/helix/assets/1676629/bb1666b0-cddb-4564-922b-7be33360d6ae)

just to add evidence that I am seeing the same thing

**Comment by lukemarsden** [comment]
I think it’s because the system responds with text about fine tuning ("You have completed...")
which gets included back in the interactions that get sent to mistral

**Comment by lukemarsden** [comment]
I'll try to address this in #87

**Comment by lukemarsden** [comment]
fixed
