### ISSUE TITLE
When using "Fine Tune" option, it does not open and save a new session like it does with the "Create" option - Cannot Restore a fine tune session

### ISSUE THREAD

**Issue by px3l** [helixml/helix#26]
If I start a conversation / generation with the Create option selected, then it opens and saves a session in the sidebar, but this does not happen when I use the Finetune option.

I cannot find a way to restore my Fine Tune session

**Comment by lukemarsden** [comment]
i mean, it does create a session when you submit any data. I don't think this behavior is hurting anyone so closing, but feel free to disagree with me!
