### ISSUE TITLE
Propagate all errors back to user

### ISSUE THREAD

**Issue by philwinder** [helixml/helix#319]
I'm not sure how pervasive this is. But my major issue is with the openai API. Upon error, the major issues are:
1. The connection is not closed. It stays open for ever until the user disconnects. This makes a curl or a widget request appear to hang.
2. Error messages are not propagated back to the user, despite the errors being visible in the Helix UI.

Related to this:
3. If there are errors in the runner, these are not propagated back to Helix at all. I think this affects all paths.

**Comment by lukemarsden** [comment]
are we still seeing this?
