### ISSUE TITLE
[UI] Chopping off content when streaming text responses

### ISSUE THREAD

**Issue by philwinder** [helixml/helix#323]
There's a bug in the UI somewhere when it starts to stream the response. I can see that the response is streaming fine because in the chat widget I see all the content. But if you look here, look how the first part of the actual message is missing Here's an answer based upon the provided context: In the image below the text starts from this colon.

![Screenshot 2024-06-07 at 13 09 12](https://github.com/helixml/helix/assets/8793723/d6cfae08-b221-4f6b-849a-7dbf0538a478)

Once the text stops streaming, it shows the full text.

![Screenshot 2024-06-07 at 13 09 40](https://github.com/helixml/helix/assets/8793723/88e74904-35bd-4bc9-ab8b-0f38ec4dd774)

**Comment by lukemarsden** [comment]
fixed
