### ISSUE TITLE
feature: support external Ollama via native Ollama API

### ISSUE THREAD

**Issue by sammcj** [helixml/helix#462]
It would be great if you could provide the URL or container name for an existing Ollama server and have Helix use it's native API (rather than the openai compatible API).

The native API offers quite a lot more than the openai compatible API which should really only be used as a last resort for incompatible apps.

**Comment by lukemarsden** [comment]
You were right, needed this to fix context length from tiny 2K limit - thanks!

**Comment by lukemarsden** [comment]
Fixed
